name: Feature request
description: Any ideas cool ideas for the project? Suggest!
title: "[FEAT]"
labels: ["enhancement"]
body:
  - type: textarea
    id: limitation
    attributes:
      label: Is your feature request related to a limitation? Please describe.
      description: |
        A clear and concise description of what the limitation is. Example:

        > Everytime I want to {scrape, convert, filter, sample, ...} I have '...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen. Assure you considered the new command's feasibility. Example:

        > A new command '...' would simplify this usage case.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered. Example:

        > If the command happens to unfeasible, a new config file structure '...' would also help.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
